apiVersion: v1
kind: Service
metadata:
  name: vite-react-app
spec:
  selector:
    app: vite-react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Use ClusterIP if you don't need external access
